# Домашнее задание 2

# Первая часть

In [1]:
import numpy as np
import numpy.linalg

### Задание №1

а) Поскольку число столбцов матрицы $A$(2) не равно числу строк матрицы $B$ (4), $\Rightarrow A\cdot B\text{ не определено}$, а поскольку число столбцов матрицы $B$ (2), так же не равно числу строк матрицы $A$ (4), $\Rightarrow B\cdot A\text{ так же, не определено}$  

---
б) $A\cdot B$ определено, полученная матрица имеет размер $2\times 3$, $B\cdot A\text{ не определено}$  

---  
в) $A\cdot B$ определено, полученная матрица имеет размер $8\times 8$, $B\cdot A$ определено, полученная матрица имеет размер $3\times 3$  

---  
г) $A\cdot B$ и $B\cdot A$ определены и полученные матрицы имеют размер $4\times 4$.  

---

### Задание 2

#### Сумма

$A+B=\begin{pmatrix}1+4 & -2+(-1)\\3+0 & 0+5\end{pmatrix}=\begin{pmatrix}5 & -3\\3 & 5\end{pmatrix}$

**numpy:**  

In [4]:
A=np.array([[1,-2],[3,0]])
B=np.array([[4,-1],[0,5]])

In [5]:
A+B

array([[ 5, -3],
       [ 3,  5]])

#### Произведение

---  
$A\cdot B=\begin{pmatrix}1 & -2\\3 & 0\end{pmatrix}\cdot \begin{pmatrix}4 & -1\\0 & 5\end{pmatrix}=\begin{pmatrix}1\cdot 4+(-2)\cdot 0 & 1\cdot -1+(-2)\cdot 5\\3\cdot 4+0\cdot 0 & 3\cdot -1 +0\cdot 5\end{pmatrix}=\begin{pmatrix}4 & -11\\12 & -3\end{pmatrix}$  

---
$B\cdot A=\begin{pmatrix}4 & -1\\0 & 5\end{pmatrix}\cdot\begin{pmatrix}1 & -2\\3 & 0\end{pmatrix} =\begin{pmatrix}4\cdot 1+(-1)\cdot 3 & 4\cdot -2+(-1)\cdot 0\\0\cdot 1+5\cdot 3 & 0\cdot -2 +5\cdot 0\end{pmatrix}=\begin{pmatrix}1 & -8\\15 & 0\end{pmatrix}$  



**numpy:**

In [6]:
A@B

array([[  4, -11],
       [ 12,  -3]])

In [7]:
B@A

array([[ 1, -8],
       [15,  0]])

### Задание 3

$3A-2B+4C=3\cdot \begin{pmatrix}1 & 7\\3 & -6\end{pmatrix}-2\cdot \begin{pmatrix}0 & 5\\2 & -1\end{pmatrix}+4\cdot \begin{pmatrix}2 & -4\\ 1 & 1\end{pmatrix}=\begin{pmatrix}1\cdot 3 & 7\cdot 3\\3\cdot 3 & -6\cdot 3\end{pmatrix}-\begin{pmatrix}0\cdot 2 & 5\cdot 2\\2\cdot 2 & -1\cdot 2\end{pmatrix}+\begin{pmatrix}2\cdot 4 & -4\cdot 4\\ 1\cdot 4 & 1\cdot 4\end{pmatrix}=\begin{pmatrix}3-0+8 & 21-10-16\\9-4+4 & -18+2+4\end{pmatrix}=\begin{pmatrix}11 & -5\\9 & -12\end{pmatrix}$  

**numpy**

In [8]:
a=np.array([[1,7],[3,-6]])
b=np.array([[0,5],[2,-1]])
c=np.array([[2,-4],[1,1]])
3*a-2*b+4*c

array([[ 11,  -5],
       [  9, -12]])

# Вторая часть

### Задание 1

а) Для матрицы порядка 2:  
$A=\begin{pmatrix}
a_{11} & a_{12}\\ 
a_{21} & a_{22}
\end{pmatrix}$,  
определитель вычисляется как:  
$detA=a_{11}a_{22} - a_{12}a_{21}$.  
Тогда:  
$A=\begin{pmatrix}
sinx & -cosx\\ 
cosx & sinx
\end{pmatrix}$  
$detA=\sin x \cdot sin x - (-\cos x)\cdot\cos x=\sin^2 x + \cos^2 x=1$

In [9]:
for x in range(0,11,2):
    A=np.array([[np.sin(x), -np.cos(x)],[np.cos(x), np.sin(x)]])
    print(x, round(np.linalg.det(A)))

0 1
2 1
4 1
6 1
8 1
10 1


б)  
$B=\begin{pmatrix}
4 & 2 & 3\\ 
0 & 5 & 1\\ 
0 & 0 & 9
\end{pmatrix}$   
Воспользуемся свойством определителя матрицы треугольного вида:  
**Определитель матрицы треугольного вида равен произведению элементов, стоящих на ее главной диагонали**  
$detB=4\cdot 5\cdot 9=180$

In [10]:
B=np.array([[4,2,3], [0,5,1],[0,0,9]])  
np.linalg.det(B)

180.0

In [11]:
B=np.array([[4,2,3], [0,5,1],[0,0,9]])  
np.linalg.det(B)

180.0

в)  Разложим по элементам первой строки:  
$C=\begin{pmatrix}
1 & 2 & 3\\ 
4 & 5 & 6\\ 
7 & 8 & 9
\end{pmatrix}$  
$detC=1\cdot\begin{pmatrix}5 & 6\\8 & 9\end{pmatrix}-2\cdot\begin{pmatrix}4 & 6\\7 & 9\end{pmatrix}+3\cdot\begin{pmatrix}4 & 5\\7 & 8\end{pmatrix}=1\cdot (5\cdot 9-6\cdot 8)-2\cdot (4\cdot 9-6\cdot 7)+3\cdot (4\cdot 8-5\cdot 7)=0$

In [12]:
C=np.array([[1,2,3], [4,5,6],[7,8,9]])  
round(np.linalg.det(C),1)

0.0

### Задание 2

a) Используем следующее свойство определителя:  

**Для двух квадратных матриц одинакового размера**  

$det(AB)=detA\cdot detB$.  

Следовательно:  

$det(A^2)=det(A\cdot A)=det(A)\cdot det(A)=4\cdot 4=16$  

б) Используем следующее свойство определителя:  

**Определитель транспонированной матрицы равен определителю исходной:**  

$detA^{T}=detA$.  

Следовательно:  

$det(A^T)=4$  

в) Из свойства определителя:  
​
**Умножение строки или столбца матрицы на число  𝜆  приведет к умножению определителя матрицы на то же число.**  
​
Следует, что $det(2A)=2^{n}\cdot det(A)=2^{n}\cdot 4$, где $n$ - порядок матрицы $A$.  


### Задание 3

Поскольку мы можем представить вторую строку данной матрицы $(4, -14, 6)$ через первую её строку $(-2, 7, -3)$ как  

$(4, -14, 6)=-2\cdot (-2, 7, -3)$, т.е. две строки (столбца) матрицы линейно зависимы, а значит её определитель равен $0$, т.е.  

такая матрица, согласно определению, является **вырожденной**.  

In [13]:
arr=np.array([[-2,7,-3],[4,-14,6],[-3,7,13]])
np.linalg.det(arr)

0.0

### Задание 4

а)

In [17]:
arr=([[1,2,3],[1,1,1],[2,3,4]])
print(f'Ранг матрицы - {np.linalg.matrix_rank(arr)}')

Ранг матрицы - 2


б)

In [19]:
arr=([[0,0,2,1],[0,0,2,2],[0,0,4,3],[2,3,5,6]])
print(f'Ранг матрицы - {np.linalg.matrix_rank(arr)}')

Ранг матрицы - 3
