In [1]:
import numpy as np
import numpy.linalg

# Домашнее задание 3

# Первая часть

### Задание №1

Составим характеристическое уравнение:  

$\begin{vmatrix}
-1-\lambda & -6\\ 
2 & 6-\lambda
\end{vmatrix}=0$  

$(-1-\lambda)\cdot (6-\lambda)-(-6)\cdot 2=0\\
\lambda^{2}-5\lambda-6+12=0\\
\lambda^{2}-5\lambda+6=0\\
D=5^{2}-4\cdot 1\cdot 6=25-24=1; \sqrt D=1\\
\lambda_1=\frac{-(-5)-1}{2\cdot 1}=2\\
\lambda_2=\frac{-(-5)+1}{2\cdot 1}=3$  

**Собственные значения** для линейного оператора $A$: $\lambda_1=2, \lambda_2=3$  

Найдем собственные векторы:  

а) $\lambda=\lambda_1=2\\
\begin{pmatrix}
-1 & -6\\ 
2 & 6
\end{pmatrix}\cdot \begin{pmatrix}x\\ y\end{pmatrix}=\lambda\cdot \begin{pmatrix}x\\ y\end{pmatrix}\\
\begin{pmatrix}
-x-6y\\ 
2x+6y
\end{pmatrix}=\begin{pmatrix}2x\\ 2y\end{pmatrix}\\
\begin{cases}-3x-6y=0\\2x+4y=0\end{cases}\\
x=-2y$  

Получили бесконечное множество коллинеарных векторов.

Найдем 1 частное решение:  

Пусть $y=-1$, тогда $x=2$  

Проверим:  

$\begin{cases}-3\cdot 2-6\cdot (-1)=0\\2\cdot 2+4\cdot (-1)=0\end{cases}$ верно.

$\bar{u_1}=\begin{pmatrix}2\\ -1\end{pmatrix}$  

б) $\lambda=\lambda_2=3\\
\begin{pmatrix}
-1 & -6\\ 
2 & 6
\end{pmatrix}\cdot \begin{pmatrix}x\\ y\end{pmatrix}=\lambda\cdot \begin{pmatrix}x\\ y\end{pmatrix}\\
\begin{pmatrix}
-x-6y\\ 
2x+6y
\end{pmatrix}=\begin{pmatrix}3x\\ 3y\end{pmatrix}\\
\begin{cases}-4x-6y=0\\2x+3y=0\end{cases}\\
x=-\frac{3}{2}y$  

Получили бесконечное множество коллинеарных векторов.

Найдем 1 частное решение:  

Пусть $y=-2$, тогда $x=3$  

Проверим:  

$\begin{cases}-4\cdot 3-6\cdot (-2)=0\\2\cdot 3+3\cdot (-2)=0\end{cases}$ верно.

$\bar{u_2}=\begin{pmatrix}3\\ -2\end{pmatrix}$  

Проверим с numpy:

In [3]:
A=np.array([[-1,-6],[2,6]])
w, v = np.linalg.eig(A)
print(f'Собственные значения:\n{w}')
print(f'Собственные векторы:\n{v}')

Собственные значения:
[2. 3.]
Собственные векторы:
[[-0.89442719  0.83205029]
 [ 0.4472136  -0.5547002 ]]


Нормируем расчитанные вектора $\bar{u_1}=\begin{pmatrix}2\\ -1\end{pmatrix}$ и $\bar{u_2}=\begin{pmatrix}3\\ -2\end{pmatrix}$

In [5]:
u1=np.array([[2],[-1]])
u2=np.array([[3],[-2]])
u1n=u1/np.linalg.norm(u1, ord=2)
u2n=u2/np.linalg.norm(u2, ord=2)
print(f'{u1n},\n{u2n}')

[[ 0.89442719]
 [-0.4472136 ]],
[[ 0.83205029]
 [-0.5547002 ]]


### Задание №2

$\begin{pmatrix}
-1 & 0\\ 
0 & -1
\end{pmatrix}\cdot \begin{pmatrix}x\\ y\end{pmatrix}=\lambda\cdot \begin{pmatrix}x\\ y\end{pmatrix}\\
\begin{pmatrix}
-x\\ 
-y
\end{pmatrix}=\begin{pmatrix}\lambda x\\ \lambda y\end{pmatrix}\\
\begin{cases}-x=\lambda x\\-y=\lambda y\end{cases}\\
\lambda=-1$  

Решение не зависит от значений $x$ и $y$, следовательно для оператора поворота **любой** вектор является собственным.

In [7]:
B=np.array([[-1,0],[0,-1]])
w, v = np.linalg.eig(B)
print(f'Собственные значения:\n{w}')
print(f'Собственные векторы:\n{v}')

Собственные значения:
[-1. -1.]
Собственные векторы:
[[1. 0.]
 [0. 1.]]


### Задание №3

Предположим, что $x=(1,1)$ является собственным вектором оператора $A$, тогда:  
    
$\begin{pmatrix}
1 & 1\\ 
-1 & 3
\end{pmatrix}\cdot\begin{pmatrix}1\\1\end{pmatrix}=\lambda\cdot\begin{pmatrix}1\\1\end{pmatrix} \Rightarrow$  

$\begin{cases}1+1=\lambda \\
-1+3=\lambda \end{cases}\\\Rightarrow \lambda=2$  

Вектор $x=(1,1)$ **является** собственным вектором оператора $A=\begin{pmatrix}
1 & 1\\ 
-1 & 3
\end{pmatrix}$, с собственным значением $\lambda = 2$.  

### Задание №4

Предположим что вектор $x$ собственный вектор оператора $A$, тогда:  
    
$\begin{pmatrix}
0 & 3 & 0\\ 
3 & 0 & 0\\
0 & 0 & 3
\end{pmatrix}\cdot \begin{pmatrix}3\\-3\\-4\end{pmatrix}=\lambda \cdot\begin{pmatrix}3\\-3\\-4\end{pmatrix}\Rightarrow\\
\begin{cases}-9=3\lambda\\9=-3\lambda\\-12=-4\lambda\end{cases}\Rightarrow\\
\begin{cases}\lambda=-3\\\lambda=-3\\\lambda=3\end{cases}$  
Такая система не имеет смысла, следовательно, вектор $x=(3, -3, -4)$ **не является** собственным вектором линейного оператора, заданного матрицей $A$.