# <center>Практическое задание к уроку 4.  
## Часть 1.

In [1]:
import numpy as np
import numpy.linalg
import scipy.linalg

__Задание 1.__ Решить систему уравнений методом Гаусса:

$\begin{cases}
x_{1}+x_{2}-x_{3}-2x_{4}=0 \\
2x_{1}+x_{2}-x_{3}+x_{4}=-2 \\
x_{1}+x_{2}-3x_{3}+x_{4}=4
\end{cases}$.  

Система имеее количество уравнений меньшее, чем количество неизвестных, соответственно система является *недоопределённой*.  

Запишем расширенную матрицу системы:  

$\begin{pmatrix}
\left.\begin{matrix}
1 & 1 & -1 & -2\\ 
2 & 1 & -1 & 1 \\ 
1 & 1 & -3 & 1
\end{matrix}\right|
\begin{matrix}
0\\ 
-2\\
4
\end{matrix}
\end{pmatrix}$.  

Вычтем из третьей строки первую:  

$\begin{pmatrix}
\left.\begin{matrix}
1 & 1 & -1 & -2\\ 
2 & 1 & -1 & 1 \\ 
0 & 0 & -2 & 3
\end{matrix}\right|
\begin{matrix}
0\\ 
-2\\
4
\end{matrix}
\end{pmatrix}$  

Вычтем из второй строки удвоенную первую:  

$\begin{pmatrix}
\left.\begin{matrix}
1 & 1 & -1 & -2\\ 
0 & -1 & 1 & 5 \\ 
0 & 0 & -2 & 3
\end{matrix}\right|
\begin{matrix}
0\\ 
-2\\
4
\end{matrix}
\end{pmatrix}$  

Прибавим вторую строку к первой:  

$\begin{pmatrix}
\left.\begin{matrix}
1 & 0 & 0 & 3\\ 
0 & -1 & 1 & 5 \\ 
0 & 0 & -2 & 3
\end{matrix}\right|
\begin{matrix}
-2\\ 
-2\\
4
\end{matrix}
\end{pmatrix}$ 

Ранг матрицы системы уравнений  и ранг расширенной матрицы равны, $rank A=rank\tilde A=3 \Rightarrow$ система имеет множество решений.  

Пусть $x_4=c$, тогда:  

$-2x_{3}+3c=4\\x_3=-\frac{4-3c}{2}\\x_{3}=-2+\frac{3}{2}c\\-x_{2}+x_{3}+5c=-2\\x_2=2+5c-2+\frac{3}{2}c\\x_2=\frac{13}{2}c\\ x_{1}+3c=-2\\x_1=-2-3c$  

Общее решение системы:  

$x_1=-2-3c\\x_2=\frac{13}{2}c\\x_{3}=-2+\frac{3}{2}c\\x_4=c$  

Найдем частное решение при $c=0$, тогда  

$x_1=-2\\x_2=0\\x_3=-2\\x_4=0$  

Подставим в систему:  

$\begin{cases}
-2+0+2-2\cdot 0=0 \\
2\cdot -2+0+2+0=-2 \\
-2+0-3\cdot -2+0=4
\end{cases}$,  
верно.

__Задание 2.__ Проверить на совместность и выяснить, сколько решений будет иметь система линейных уравнений:

   а) $\begin{cases}
3x_{1}-x_{2}+x_{3}=4, \\
2x_{1}-5x_{2}-3x_{3}=-17 \\
x_{1}+x_{2}-x_{3}=0
\end{cases}$;
    
   б) $\begin{cases}
2x_{1}-4x_{2}+6x_{3}=1 \\
x_{1}-2x_{2}+3x_{3}=-2 \\
3x_{1}-6x_{2}+9x_{3}=5
\end{cases}$;
    
   в) $\begin{cases}
x_{1}+2x_{2}+5x_{3}=4 \\
3x_{1}+x_{2}-8x_{3}=-2 
\end{cases}$.


**а)** Составим расширенную матрицу системы:  

$\begin{pmatrix}
\left.\begin{matrix}
3 & -1 & 1\\ 
2 & -5 & -3\\ 
1 & 1 & -1
\end{matrix}\right|
\begin{matrix}
4\\ 
-17\\
0
\end{matrix}
\end{pmatrix}$  

и сравним ранги матрицы системы и расширенной матрицы:  

In [2]:
A=np.array([[3,-1,1],[2,-5,-3],[1,1,-1]])
B=np.array([[3,-1,1,4],[2,-5,-3,-17],[1,1,-1,0]])
print(f'Ранг матрицы системы уравнений: rankA={np.linalg.matrix_rank(A)},\n'
      f'ранг расширенной матрицы: rankB={np.linalg.matrix_rank(B)}')

Ранг матрицы системы уравнений: rankA=3,
ранг расширенной матрицы: rankB=3


Поскольку $rankA=rank \tilde A=n$, где $n$ — число неизвестных, соответственно система **совместна и определена** и имеет **единственное** решение.  



**б)** Составим расширенную матрицу системы:  

$\begin{pmatrix}
\left.\begin{matrix}
2 & -4 & 6\\ 
1 & -2 & 3\\ 
3 & -6 & 9
\end{matrix}\right|
\begin{matrix}
1\\ 
-2\\
5
\end{matrix}
\end{pmatrix}$  

Сразу заметно, что векторы матрицы системы $\bar{x_1}=(2,-4,6), \bar{x_2}=(1,-2,3),\text{ и }\bar{x_3}=(3,-6,9)$ линейно зависимы,  

а вектор коэфициентов $\bar{b}=\begin{pmatrix}1\\-2\\5\end{pmatrix}$ **не принадлежит** линейному подпространству образованному ими,  

 можем сделать вывод, что система **несовместна** и **не имеет** решений.

Для подтверждени сравним ранги матрицы системы и расширенной матрицы: 

In [3]:
A=np.array([[2,-4,6],[1,-2,3],[3,-6,9]])
B=np.array([[2,-4,6,1],[1,-2,3,-2],[3,-6,9,5]])
print(f'Ранг матрицы системы уравнений: rankA={np.linalg.matrix_rank(A)},\n'
      f'ранг расширенной матрицы: rankB={np.linalg.matrix_rank(B)}')

Ранг матрицы системы уравнений: rankA=1,
ранг расширенной матрицы: rankB=2


Действительно, $rankA<rank\tilde A\Rightarrow$ система **несовместна** и **не имеет** решений.  



**в)** Составим расширенную матрицу системы:  

$\begin{pmatrix}
\left.\begin{matrix}
1 & 2 & 5\\ 
3 & 1 & -8
\end{matrix}\right|
\begin{matrix}
4\\ 
-2
\end{matrix}
\end{pmatrix}$  

Поскольку количество уравнений меньше количества неизвестных, сразу можем сделать выводб что система **недоопределена**, а значит, в зависимости от критерия совместности может либо не иметь решений, либо имеет множество решений.  

Сравним ранги матрицы системы и расширенной матрицы:

In [4]:
A=np.array([[1,2,5],[3,1,-8]])
B=np.array([[1,2,5,4],[3,1,-8,-2]])
print(f'Ранг матрицы системы уравнений: rankA={np.linalg.matrix_rank(A)},\n'
      f'ранг расширенной матрицы: rankB={np.linalg.matrix_rank(B)}')

Ранг матрицы системы уравнений: rankA=2,
ранг расширенной матрицы: rankB=2


Поскольку $rankA=rank \tilde A<n$, , где $n$ — число неизвестных, то система **совместна, но неопределена**, и имеет **множество** решений.

__Задание 3.__ Проверить на совместность и выяснить, сколько решений будет иметь система линейных уравнений, заданная расширенной матрицей

$\tilde{A}=\begin{pmatrix}
\left.\begin{matrix}
1 & 3 & -2 & 4\\ 
0 & 5 & 0 & 1\\ 
0 & 0 & 3 & 0\\ 
0 & 0 & 0 & 2
\end{matrix}\right|
\begin{matrix}
3\\ 
2\\
4\\
1
\end{matrix}
\end{pmatrix}$.

Сравним ранги матрицы системы и расширенной матрицы:

In [5]:
A=np.array([[1,3,-2,4],[0,5,0,1],[0,0,3,0],[0,0,0,2]])
B=np.array([[1,3,-2,4,3],[0,5,0,1,2],[0,0,3,0,4],[0,0,0,2,1]])
print(f'Ранг матрицы системы уравнений: rankA={np.linalg.matrix_rank(A)},\n'
      f'ранг расширенной матрицы: rankB={np.linalg.matrix_rank(B)}')

Ранг матрицы системы уравнений: rankA=4,
ранг расширенной матрицы: rankB=4


Поскольку $rankA=rank \tilde A=n$, где $n$ — число неизвестных, следовательно система **совместна и определена** и имеет **единственное** решение.

__Задание 4.__ Дана система линейных уравнений, заданная расширенной матрицей

$\tilde{A}=\begin{pmatrix}
\left.\begin{matrix}
1 & 2 & 3\\ 
4 & 5 & 6\\ 
7 & 8 & 9
\end{matrix}\right|
\begin{matrix}
a\\ 
b\\
c
\end{matrix}
\end{pmatrix}$.

Найти соотношение между параметрами $a$, $b$ и $c$, при которых система является несовместной.

Система будет несовместной если $rankA<rank\tilde A$  

Преобразуем $\tilde A$  

$\begin{pmatrix}
\left.\begin{matrix}
1 & 2 & 3\\ 
4 & 5 & 6\\ 
7 & 8 & 9
\end{matrix}\right|
\begin{matrix}
a\\ 
b\\
c
\end{matrix}
\end{pmatrix}$

Вычтем из второй строки удвоенную первую:  

$\begin{pmatrix}
\left.\begin{matrix}
1 & 2 & 3\\ 
2 & 1 & 0\\ 
7 & 8 & 9
\end{matrix}\right|
\begin{matrix}
a\\ 
b-2a\\
c
\end{matrix}
\end{pmatrix}$  

Вычтем из третьей строки утроенную первую:  

$\begin{pmatrix}
\left.\begin{matrix}
1 & 2 & 3\\ 
2 & 1 & 0\\ 
4 & 2 & 0
\end{matrix}\right|
\begin{matrix}
a\\ 
b-2a\\
c-3a
\end{matrix}
\end{pmatrix}$  

Вычтем из третьей строки удвоенную вторую:  

$\begin{pmatrix}
\left.\begin{matrix}
1 & 2 & 3\\ 
2 & 1 & 0\\ 
0 & 0 & 0
\end{matrix}\right|
\begin{matrix}
a\\ 
b-2a\\
c-3a-2(b-2a)
\end{matrix}
\end{pmatrix}=\begin{pmatrix}
\left.\begin{matrix}
1 & 2 & 3\\ 
2 & 1 & 0\\ 
0 & 0 & 0
\end{matrix}\right|
\begin{matrix}
a\\ 
b-2a\\
c+a-2b
\end{matrix}
\end{pmatrix}$  

Поскольку $rankA=2$, то для выполнения условия **несовместности** необходимоб чтобы $rank \tilde A>2$, а это возможно при условии что  

$c+a-2b\neq0$

## Часть 2.

__Задание 1.__ Решить систему уравнений методом Крамера:

   а) $\begin{cases}
x_{1}-2x_{2}=1 \\
3x_{1}-4x_{2}=7
\end{cases}$;
    
   б) $\begin{cases}
2x_{1}-x_{2}+5x_{3}=10 \\
x_{1}+x_{2}-3x_{3}=-2 \\
2x_{1}+4x_{2}+x_{3}=1
\end{cases}$.

---  
а)  

$\begin{cases}
x_{1}-2x_{2}=1 \\
3x_{1}-4x_{2}=7
\end{cases}$  

Найдем определитель матрицы коэффициентов:  

$A=\begin{pmatrix}1 & -2\\
3 & -4\end{pmatrix}\\
detA=\begin{vmatrix}1 & -2\\
3 & -4\end{vmatrix}=1\cdot -4-(-2)\cdot 3=2\neq 0\\
\Rightarrow\text{ Система определена}\\
detA_1=\begin{vmatrix}1 & -2\\
7 & -4\end{vmatrix}=-4+14=10\\
detA_2=\begin{vmatrix}1 & 1\\
3 & 7\end{vmatrix}=7-3=4\\
x_1=\frac{detA_1}{detA}=\frac{10}{2}=5\\
x_2=\frac{detA_2}{detA}=\frac{4}{2}=2$  

---

б) $\begin{cases}
2x_{1}-x_{2}+5x_{3}=10 \\
x_{1}+x_{2}-3x_{3}=-2 \\
2x_{1}+4x_{2}+x_{3}=1
\end{cases}$  

Решим с помошью методов numpy:  

In [6]:
A=np.array([[2,-1,5],[1,1,-3],[2,4,1]])
detA=round(np.linalg.det(A))
print(f'Определитель матрицы коэффициентов detA ={detA}')

Определитель матрицы коэффициентов detA =43


$detA\neq 0\Rightarrow\text{ Система определена.}$

In [7]:
A=np.array([[2,-1,5],[1,1,-3],[2,4,1]])
B=np.array([[10],[-2],[1]])
dets=[]
for j in range(len(A[1])):
    A_copy=A.copy()
    for i in range(len(A)):
        A_copy[i][j]=B[i]
    dets.append(round(np.linalg.det(A_copy)))
detA=round(np.linalg.det(A))
print(f'Определитель матрицы коэффициентов detA = {detA}')
for i,det in enumerate(dets):
    print(f'detA{i+1} = {det}, x{i+1} = {det/detA}')

Определитель матрицы коэффициентов detA = 43
detA1 = 86, x1 = 2.0
detA2 = -43, x2 = -1.0
detA3 = 43, x3 = 1.0


$x_1=2\\x_2=-1\\x_3=1$

__Задание 2*.__ Найти $L$-матрицу $LU$-разложения для матрицы коэффициентов:

   а)$\begin{pmatrix}
1 & 2 & 4 \\ 
2 & 9 & 12 \\ 
3 & 26 & 30
\end{pmatrix}$
    
   б)$\begin{pmatrix}
1 & 1 & 2 & 4\\ 
2 & 5 & 8 & 9\\ 
3 & 18 & 29 & 18\\
4 & 22 & 53 & 33
\end{pmatrix}$

 
**а)**  
$U=\begin{pmatrix}
1 & 2 & 4 \\ 
2 & 9 & 12 \\ 
3 & 26 & 30
\end{pmatrix}$  

$L=\begin{pmatrix}
1 & 0 & 0 \\ 
0 & 1 & 0 \\ 
0 & 0 & 1
\end{pmatrix}$  

Вычтем из второй и третьей строк матрицы $U$ первую строку, умноженную на 2 и 3 соответственно.  
В матрицу $L$ добавим эти множители в первый столбец на 2-ю и третью позиции.  

$U=\begin{pmatrix}
1 & 2 & 4 \\ 
0 & 5 & 4 \\ 
0 & 20 & 18
\end{pmatrix}$  

$L=\begin{pmatrix}
1 & 0 & 0 \\ 
2 & 1 & 0 \\ 
3 & 0 & 1
\end{pmatrix}$  

Вычтем из третьей строки матрицы $U$ вторую строку, умноженную 4.  
В матрицу $L$ добавим этот множитель во второй столбец на третью позицию.  

$U=\begin{pmatrix}
1 & 2 & 4 \\ 
0 & 5 & 4 \\ 
0 & 0 & 2
\end{pmatrix}$  

$L=\begin{pmatrix}
1 & 0 & 0 \\ 
2 & 1 & 0 \\ 
3 & 4 & 1
\end{pmatrix}$  

Проверим:

In [8]:
U=np.array([[1,2,4],[0,5,4],[0,0,2]])
L=np.array([[1,0,0],[2,1,0],[3,4,1]])
print(f'LU = {L@U}')

LU = [[ 1  2  4]
 [ 2  9 12]
 [ 3 26 30]]


Получили исходную матрицу.


**б)**  
$U=\begin{pmatrix}
1 & 1 & 2 & 4\\ 
2 & 5 & 8 & 9\\ 
3 & 18 & 29 & 18\\
4 & 22 & 53 & 33
\end{pmatrix}$  

$L=\begin{pmatrix}
1 & 0 & 0 & 0\\ 
0 & 1 & 0 & 0\\ 
0 & 0 & 1 & 0\\
0 & 0 & 0 & 1
\end{pmatrix}$  

Из второй, третьей и четвёртой строк вычитаем первую, умноженную на 2, 3 и 4, соответственно   

$U=\begin{pmatrix}
1 & 1 & 2 & 4\\ 
0 & 3 & 4 & 1\\ 
0 & 15 & 23 & 6\\
0 & 18 & 45 & 17
\end{pmatrix}$  

$L=\begin{pmatrix}
1 & 0 & 0 & 0\\ 
2 & 1 & 0 & 0\\ 
3 & 0 & 1 & 0\\
4 & 0 & 0 & 1
\end{pmatrix}$  

Из третьей и четвёртой строк вычитаем вторую, умноженную на 5 и 6, соответственно  

$U=\begin{pmatrix}
1 & 1 & 2 & 4\\ 
0 & 3 & 4 & 1\\ 
0 & 0 & 3 & 1\\
0 & 0 & 21 & 11
\end{pmatrix}$  

$L=\begin{pmatrix}
1 & 0 & 0 & 0\\ 
2 & 1 & 0 & 0\\ 
3 & 5 & 1 & 0\\
4 & 6 & 0 & 1
\end{pmatrix}$  

Из четвёртой строки вычтем третью, умноженную на 7

$U=\begin{pmatrix}
1 & 1 & 2 & 4\\ 
0 & 3 & 4 & 1\\ 
0 & 0 & 3 & 1\\
0 & 0 & 0 & 4
\end{pmatrix}$  

$L=\begin{pmatrix}
1 & 0 & 0 & 0\\ 
2 & 1 & 0 & 0\\ 
3 & 5 & 1 & 0\\
4 & 6 & 7 & 1
\end{pmatrix}$  

Проверим:

In [9]:
L=np.array([[1,0,0,0],[2,1,0,0],[3,5,1,0],[4,6,7,1]])
U=np.array([[1,1,2,4],[0,3,4,1],[0,0,3,1],[0,0,0,4]])
print(f'LU = {L@U}')

LU = [[ 1  1  2  4]
 [ 2  5  8  9]
 [ 3 18 29 18]
 [ 4 22 53 33]]


Получили исходную матрицу.

__Задание 3*.__ Решить систему линейных уравнений методом $LU$-разложения

$\begin{cases}
2x_{1}+x_{2}+3x_{3}=1 \\
11x_{1}+7x_{2}+5x_{3}=-6 \\
9x_{1}+8x_{2}+4x_{3}=-5
\end{cases}$

In [17]:
A=np.array([[2,1,3],[11,7,5],[9,8,4]])
b=np.array([1,-6,-5])
A

array([[ 2,  1,  3],
       [11,  7,  5],
       [ 9,  8,  4]])

In [18]:
b

array([ 1, -6, -5])

Найдем матрицы $L$ и $U$

In [19]:
p,L,U=scipy.linalg.lu(A)
print(f'Матрица p: \n{p}\nМатрица L:\n{L}\nМатрица U:\n{U}')

Матрица p: 
[[0. 0. 1.]
 [1. 0. 0.]
 [0. 1. 0.]]
Матрица L:
[[ 1.          0.          0.        ]
 [ 0.81818182  1.          0.        ]
 [ 0.18181818 -0.12        1.        ]]
Матрица U:
[[11.          7.          5.        ]
 [ 0.          2.27272727 -0.09090909]
 [ 0.          0.          2.08      ]]


Решим систему $Ly=b$

In [20]:
def y_search(L,b,p):
    y_arr=np.array([0 for i in range(len(b))],dtype=float)
    b_copy=(p.T@b).astype(np.float)
    for i in range(len(b)):
        for j in range(len(b)):
            tot=(L[i][j]*y_arr[j])
            b_copy[i]-=tot
        y_arr[i]=b_copy[i]/L[i][i]
    return y_arr.reshape(len(b),-1)

y_arr=y_search(L,b,p)
y_arr
            

array([[-6.        ],
       [-0.09090909],
       [ 2.08      ]])

Решим систему $Ux=b$:

In [69]:
def x_search(U,y_arr):
    x_arr=np.array([0 for i in range(len(y_arr))],dtype=float)
    b_copy=y_arr.copy()
    for i in range(len(y_arr)-1,-1,-1):
        for j in range(len(y_arr)-1,-1,-1):
            tot=(U[i][j]*x_arr[j])
            b_copy[i]-=tot
        x_arr[i]=b_copy[i]/U[i][i]
    return x_arr.reshape(len(x_arr),-1)

In [22]:
x_arr=x_search(U,y_arr)
x_arr

array([[-1.00000000e+00],
       [ 1.46549439e-16],
       [ 1.00000000e+00]])

$x_1=-1,\\
x_2=0,\\
x_3=1.$  

Проверим:  

$\begin{cases}
2\cdot -1+0+3\cdot 1=1 \\
11\cdot -1+7\cdot 0+5\cdot 1=-6 \\
9\cdot -1+8\cdot 0+4\cdot 1=-5
\end{cases}$ - верно!

Проверим еще раз на системе из материалов к лекции:  

$\begin{cases}
2x_{1}+x_{2}-x_{3}=5, \\
4x_{1}-6x_{2}-2x_{3}=-2, \\
-2x_{1}+7x_{2}-3x_{3}=7
\end{cases}$  

решение которой известно:  

$x_{3}=0$,  
$x_{2}=1.5$,  
$x_{1}=1.75$.

In [84]:
A=np.array([[2,1,-1],[4,-6,-2],[-2,7,-3]])
b=np.array([5,-2,7])
p,L,U=scipy.linalg.lu(A)
y_arr=y_search(L,b,p)
y_arr

array([[-2.],
       [ 6.],
       [ 0.]])

In [25]:
x_arr=x_search(U,y_arr)
x_arr

array([[ 1.75],
       [ 1.5 ],
       [-0.  ]])

Ответ совпал:  
$x_1=1.75,\\
x_2=1.5,\\
x_3=0.$